import pandas as pd
import io
import traceback

class DataProcessor:
    def __init__(self):
        self.data_store = {}

    def load_file(self, file_obj, filename):
        """
        Load a file into a pandas DataFrame and store it.
        """
        try:
            if filename.endswith('.csv'):
                df = pd.read_csv(file_obj)
            elif filename.endswith(('.xls', '.xlsx')):
                df = pd.read_excel(file_obj)
            else:
                raise ValueError("Unsupported file format")

            self.data_store[filename] = df
            return self._extract_metadata(df, filename)
        except Exception as e:
            print(f"Error loading file {filename}: {e}")
            raise e

    def _extract_metadata(self, df, filename):
        """
        Extract metadata from a DataFrame.
        """
        return {
            "filename": filename,
            "columns": list(df.columns),
            "dtypes": {col: str(dtype) for col, dtype in df.dtypes.items()},
            "shape": df.shape,
            "head": df.head(3).to_dict(orient='records')
        }

    def execute_code(self, code, metadata=None):
        """
        Execute Python code generated by the agent.
        The code is expected to assume 'pd' is imported and 'dfs' is a dict of DataFrames.
        """
        try:
            # Prepare the environment
            local_vars = {
                "pd": pd,
                "dfs": self.data_store,
                "result": None
            }
            
            # Execute the code
            # We wrap it in a try-except block within the exec environment if needed, 
            # but here we just catch exceptions from the exec call.
            exec(code, {}, local_vars)
            
            # Check if 'result' variable was set
            result = local_vars.get("result")
            
            return {
                "success": True,
                "result": result
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "traceback": traceback.format_exc()
            }
